In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic = sns.load_dataset("titanic")

In [3]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [4]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [6]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [7]:
titanic.shape

(891, 15)

In [8]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
titanic = titanic.drop("deck", axis=1)

In [10]:
titanic["age"] = titanic["age"].fillna(
    titanic["age"].median()
)

In [11]:
titanic["embark_town"] = titanic["embark_town"].fillna(
    titanic["embark_town"].mode()[0]
)

In [12]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [13]:
titanic["embarked"] = titanic["embarked"].fillna(
    titanic["embarked"].mode()[0]
)

In [14]:
titanic.isnull().sum()


survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [15]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
embark_town      object
alive            object
alone              bool
dtype: object

In [16]:
titanic = titanic.drop(
    ["alive", "class", "who"],
    axis=1
)

In [17]:
titanic = pd.get_dummies(
    titanic,
    drop_first=True
)

In [18]:
titanic.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,embarked_S,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,True,False,True,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False,False,False,False
2,1,3,26.0,0,0,7.9250,False,True,False,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,True,False,True
4,0,3,35.0,0,0,8.0500,True,True,True,False,True,False,True


In [19]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   survived                 891 non-null    int64  
 1   pclass                   891 non-null    int64  
 2   age                      891 non-null    float64
 3   sibsp                    891 non-null    int64  
 4   parch                    891 non-null    int64  
 5   fare                     891 non-null    float64
 6   adult_male               891 non-null    bool   
 7   alone                    891 non-null    bool   
 8   sex_male                 891 non-null    bool   
 9   embarked_Q               891 non-null    bool   
 10  embarked_S               891 non-null    bool   
 11  embark_town_Queenstown   891 non-null    bool   
 12  embark_town_Southampton  891 non-null    bool   
dtypes: bool(7), float64(2), int64(4)
memory usage: 48.0 KB


In [20]:
X = titanic.drop("survived", axis=1)
y = titanic["survived"]

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 12)
(179, 12)
(712,)
(179,)


In [23]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [24]:
y_pred = model.predict(X_test)

In [25]:
y_prob = model.predict_proba(X_test)

In [26]:
print(y_pred[:10])

[0 0 0 1 1 1 1 0 1 1]


In [27]:
print(y_prob[:5])

[[0.9139766  0.0860234 ]
 [0.82091515 0.17908485]
 [0.90533227 0.09466773]
 [0.11691037 0.88308963]
 [0.23796994 0.76203006]]


In [28]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8100558659217877


In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[90 15]
 [19 55]]


In [30]:
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})
comparison.head(20)

,Actual,Predicted
709,1,0
439,0,0
840,0,0
720,1,1
39,1,1
290,1,1
300,1,1
333,0,0
208,1,1
136,1,1


In [31]:
wrong = comparison[
    comparison["Actual"] != comparison["Predicted"]
]
wrong.head(20)

,Actual,Predicted
709,1,0
621,1,0
447,1,0
673,1,0
396,0,1
235,0,1
204,1,0
23,1,0
362,0,1
772,0,1


In [32]:
wrong_indices = wrong.index

X_test.loc[wrong_indices].head()

,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,embarked_S,embark_town_Queenstown,embark_town_Southampton
709,3,28.0,1,1,15.2458,True,False,True,False,False,False,False
621,1,42.0,1,0,52.5542,True,False,True,False,True,False,True
447,1,34.0,0,0,26.5500,True,True,True,False,True,False,True
673,2,31.0,0,0,13.0000,True,True,True,False,True,False,True
396,3,31.0,0,0,7.8542,False,True,False,False,True,False,True


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



In [34]:
sample = pd.DataFrame({
    "pclass":[1],
    "age":[25],
    "sibsp":[0],
    "parch":[0],
    "fare":[100],
    "adult_male":[False],
    "alone":[True],
    "sex_male":[False],
    "embarked_Q":[False],
    "embarked_S":[True],
    "embark_town_Queenstown":[False],
    "embark_town_Southampton":[True]
})

In [35]:
print(model.predict(sample))
print(model.predict_proba(sample))

[1]
[[0.0621953 0.9378047]]


In [36]:
sample2 = pd.DataFrame({
    "pclass":[3],
    "age":[45],
    "sibsp":[0],
    "parch":[0],
    "fare":[8],
    "adult_male":[True],
    "alone":[True],
    "sex_male":[True],
    "embarked_Q":[False],
    "embarked_S":[True],
    "embark_town_Queenstown":[False],
    "embark_town_Southampton":[True]
})

print(model.predict(sample2))
print(model.predict_proba(sample2))

[0]
[[0.92827252 0.07172748]]


In [37]:
sample3 = pd.DataFrame({
    "pclass":[1],
    "age":[22],
    "sibsp":[0],
    "parch":[0],
    "fare":[120],
    "adult_male":[False],
    "alone":[True],
    "sex_male":[False],
    "embarked_Q":[False],
    "embarked_S":[True],
    "embark_town_Queenstown":[False],
    "embark_town_Southampton":[True]
})

print(model.predict(sample3))
print(model.predict_proba(sample3))

[1]
[[0.05660209 0.94339791]]


In [38]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

coefficients.sort_values(
    by="Coefficient",
    ascending=False
)

,Feature,Coefficient
4,fare,0.003192
1,age,-0.012110
8,embarked_Q,-0.091147
10,embark_town_Queenstown,-0.091147
9,embarked_S,-0.179190
11,embark_town_Southampton,-0.179190
3,parch,-0.353189
7,sex_male,-0.435772
6,alone,-0.506103
2,sibsp,-0.543039
